# Generated by Django 5.2.8 on 2025-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rider_price_rider_user_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
