# Generated by Django 5.2.8 on 2025-11-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
