# Generated by Django 5.2.8 on 2025-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Landlord', 'Landlord'), ('Rider', 'Rider'), ('Tenant', 'Tenant')], default='Tenant', max_length=20),
        ),
    ]
