# Generated by Django 5.2.8 on 2025-11-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
